### ISSUE TITLE
Create / Update code of conduct

### ISSUE THREAD

**Issue by goanpeca** [isabela-pf/jupyter-communitycalls#18]
Should we just update the README and link to this @isabela-pf 

https://jupyter.readthedocs.io/en/latest/community/content-community.html#code-of-conduct

<img width="1207" alt="Screen Shot 2021-05-10 at 4 46 45 PM" src="https://user-images.githubusercontent.com/3627835/117728647-5053e280-b1af-11eb-91ef-9cb750c7aa7b.png">

Related to https://github.com/isabela-pf/jupyter-communitycalls/issues/16

**Comment by isabela-pf** [comment]
I actually reference this right now: https://jupyter.org/conduct. I think just linking could work though, good idea!

Long term, I do want to add more specifics on top of these guidelines because I personally find them vague and potentially insufficient in the case that we do need to address a code of conduct violation.

**Comment by isabela-pf** [comment]
Fixed with 72e7341.
